---
title: Assembly of E. coli using an experimental ABySS pipeline
author: Shaun Jackman
output:
  html_document:
    keep_md: true
---

```{r load-libraries, message=FALSE}
library(dplyr)
library(ggplot2)
library(knitr)
library(tidyr)
```

```{r read-data}
data.orig <- read.delim("assembly-stats.tsv", as.is = TRUE)
```

```{r tidy-data}
data <- data.orig %>%
	separate(name, c("Directory", "File"), "/") %>%
	separate(File, c("Species", "Stage", "Ext")) %>%
	select(-Ext) %>%
	mutate(Directory = factor(Directory),
		Stage = factor(Stage, unique(Stage)))
```

```{r plot-data}
ggplot(data = data) +
	aes(x = Stage, y = NG50, color = Directory, group = Directory) +
	geom_point() +
	geom_line() +
	ylim(0, NA)
```

```{r plot-NG50, fig.width=10.5, fig.height=10, dpi=300}
data.name <- data %>%
	mutate(Name = factor(Directory,
		levels = c("k64", "k364", "k364-K32-sealer",
			"NC_000913-k64", "NC_000913-k364", "SPAdes 3.1.1"),
		labels = c("ABySS 1.5.2 k=64", "ABySS 1.5.2 k=364", "ABySS 1.6.0 k=364 K=32",
			"Reference k=64", "Reference k=364", "SPAdes 3.1.1")))

ggplot(data = data.name %>% filter(!is.na(Name))) +
	aes(x = Stage, y = NG50, color = Name, group = Name) +
	geom_point(size = 3) +
	geom_line(size = 1.5) +
	geom_hline(aes(yintercept = NG50, color = Name),
		data = data.name %>% filter(Stage == "1"),
		linetype = "dashed") +
	xlim("unitigs", "contigs", "scaffolds", "scaftigs") +
	scale_colour_brewer(palette = 'Dark2') +
	scale_y_continuous("NG50 (kbp)", limits = c(0, NA), labels = function(x) x / 1000) +
	theme_grey(28) +
	theme(legend.position = c(.25, .85))
```

```{r tabulate-data}
kable(data)
```
